# Generated by Django 5.2.8 on 2025-11-21 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('overall_sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10)),
                ('sentiment_score', models.FloatField()),
                ('total_words', models.IntegerField()),
                ('positive_words', models.IntegerField()),
                ('negative_words', models.IntegerField()),
                ('neutral_words', models.IntegerField()),
                ('intensifiers', models.IntegerField()),
                ('negations', models.IntegerField()),
                ('positive_percentage', models.FloatField()),
                ('negative_percentage', models.FloatField()),
                ('neutral_percentage', models.FloatField()),
                ('positive_summary', models.JSONField(default=list)),
                ('negative_summary', models.JSONField(default=list)),
                ('neutral_summary', models.JSONField(default=list)),
                ('positive_words_list', models.JSONField(default=list)),
                ('negative_words_list', models.JSONField(default=list)),
                ('neutral_words_list', models.JSONField(default=list)),
                ('intensifiers_list', models.JSONField(default=list)),
                ('negations_list', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='analysis_re_user_id_99eb26_idx'), models.Index(fields=['overall_sentiment'], name='analysis_re_overall_338673_idx')],
            },
        ),
    ]
